name: Calc Action
inputs:
  x:
    default: 1
  y:
    default: 0
runs:
  using: "composite"
  steps: 
      run: echo "Hello World"
      shell: bash
      run: echo "x = ${{ inputs.x}} y = ${{inputs.y}}"
      shell: bash
